x-lockdown: &lockdown
  read_only: true
  security_opt:
    - "no-new-privileges=true"

services: 
  postgres:
    image: "11notes/postgres:18"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_BACKUP_SCHEDULE: "0 3 * * *"
      POSTGRES_BACKUP_RETENTION: 5
    ports:
      - "5432:5432/tcp"
      - "9090:9187/tcp"
    networks:
      - suite-dnd
    volumes:
      - postgres.etc:/postgres/etc
      - postgres.var:/postgres/var
      - postgres.backup:/postgres/backup
    tmpfs:
      - "/postgres/run:uid=1000,gid=1000"
      - "/postgres/log:uid=1000,gid=1000"
    restart: always
    
  the-forge:
    build:
      context: ../the-forge
      dockerfile: ../docker/the-forge/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../the-forge:/the-forge
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - suite-dnd
    restart: always


  back-forge:
    build:
      context: ../back-forge
      dockerfile: ../docker/back-forge/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../back-forge:/back-forge
    command: ["php-fpm"]
    networks:
      - suite-dnd
    restart: always

volumes:
  postgres.etc:
  postgres.var:
  postgres.backup:

networks:
  suite-dnd:
